type Query {
  getPicture(input: InputGetPicture!): Picture
}

type Mutation {
  addPicture(input: InputPicture!): Picture
}

input InputGetPicture {
  id: ID!
}

input InputPicture {
  name: String!
  description: String!
}

type Picture {
  name: String
  description: String
  status: String
  createdAt: String
  updatedAt: String
}
