type Query {
  getPicture(input: InputGetPicture!): Picture
  allPictures(paginated: Paginated, filter: FilterPicture): PaginatedPicture
}

type Mutation {
  addPicture(input: InputAddPicture!): Picture
  updPicture(input: InputUpdPicture!): Picture
  updStatusPicture(input: InputUpdStatusPicture!): Picture
}

enum Status {
  available
  unavailable
}

input Paginated {
  page: Int
  perPage: Int
  sortField: String
  sortOrder: String
}

input FilterPicture {
  q: String
  ids: [ID]
  status: String
}

input InputGetPicture {
  id: ID!
}

input InputAddPicture {
  name: String!
  description: String!
}

input InputUpdPicture {
  id: String
  name: String
  description: String
  status: Status
}

input InputUpdStatusPicture {
  id: ID!
  status: Status!
}

type PaginatedPicture {
  pageInfo: PageInfo
  pictures: [Picture]
}

type Picture {
  _id: ID
  name: String
  description: String
  status: String
  createdAt: String
  updatedAt: String
}

type PageInfo {
  total: Int
  currentPage: Int
  perPage: Int
  hasPreviousPage: Boolean
  hasNextPage: Boolean
}
